[package]
name = "cryptopals-rust"
version = "0.0.1"
edition = "2021"

[dependencies.utils]
path = "../utils"

[dependencies.detectors]
path = "../detectors"

[dependencies.breakers]
path = "../breakers"

[dependencies.aes]
path = "../aes"